pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Github - Kodu Çek') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Unit Testler') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Integration Testler') {
            steps {
                bat 'mvn verify'
            }
        }
    }

    post {
        success {
            echo '✅ Build + Unit + Integration testler başarılı'
        }
        failure {
            echo '❌ Pipeline başarısız'
        }
    }
}
